package com.example.crud;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.Toast;

import com.example.crud.model.Members;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

public class Register extends AppCompatActivity {
    EditText fname,lname,phone;
    Button save,view;
    RadioGroup gender;
    RadioButton selectGender;

    //declare firebase instances
    FirebaseDatabase firebaseDatabase;
    DatabaseReference member;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        fname=findViewById(R.id.fname);
        lname=findViewById(R.id.lname);
        phone=findViewById(R.id.mobile);
        gender=findViewById(R.id.gender);

        //database initialize
        try {
            firebaseDatabase=FirebaseDatabase.getInstance();
            //members is the node/table name--a child of database CRUD
            member=firebaseDatabase.getReference().child("members");
        }catch (Exception e)
        {
            e.printStackTrace();
        }

        //buttons

        view=findViewById(R.id.view);
        save=findViewById(R.id.saveUser);

        //buttons implementations
        view.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startActivity(new Intent(Register.this,ListMembers.class));
            }
        });


        save.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String f_name,l_name,mob,myGender;
                int selectedIdForGender;
                f_name=fname.getText().toString().trim();
                l_name=lname.getText().toString().trim();
                mob=phone.getText().toString().trim();

                //get id for gender(this should be radioGroup)
                selectedIdForGender=gender.getCheckedRadioButtonId();
                //assign selected id to general radioButton(define a general variable for radioGroup, not specific to male or female)
                selectGender=findViewById(selectedIdForGender);
                //assign string for myGender
                myGender=selectGender.getText().toString().trim();

                if(!TextUtils.isEmpty(f_name)||!TextUtils.isEmpty(l_name)||!TextUtils.isEmpty(mob))
                {
                   try
                   {
                       //save users
                       Members membersModel =new Members(f_name,l_name,mob,myGender);
                       //we use push() to generate ids automatically
                       //member.child(userId).setValue(membersModel) can be used where we have current user id
                       //member.child(mob).setValue(membersModel)---we use mobile number as primary key key instead of autogenerated one with push()
                       //member.push().setValue(membersModel);
                       member.child(mob).setValue(membersModel);
                       Toast.makeText(getApplicationContext(),"Member saved successfully",Toast.LENGTH_SHORT).show();
                       fname.setText("");
                       lname.setText("");
                       phone.setText("");
                       fname.setFocusable(true);
                       //startActivity(new Intent(Register.this,ListMembers.class));

                   }catch (Exception e)
                   {
                       e.printStackTrace();
                   }
                }
                else
                {
                    Toast.makeText(getApplicationContext(),"Members not saved",Toast.LENGTH_SHORT).show();
                }
            }
        });
    }
}